### ISSUE TITLE
[Bug; 1.12.2-103b3] Windows are not transparent.

### ISSUE THREAD

**Issue by ILLOMIURGE** [stfwi/engineers-decor#15]
Nothing to add, really. Updated from b1 to b3 and boom. Windows are broken, but if dropped as items they are fine.
![2019-04-01_22 21 30](https://user-images.githubusercontent.com/49168242/55353678-9fa59000-54cc-11e9-875c-e94cedb75866.png)

**Comment by stfwi** [comment]
Ya, the new high-privacy windows ;-). Optifine installed? - because that's what I did not check.

**Comment by ILLOMIURGE** [comment]
Yep. Works fine without Optifine.

**Comment by stfwi** [comment]
Ok, I'll have to have a serious word with my GIMP ;). Scheduled for the next beta.

**Comment by stfwi** [comment]
Ok got it. Fix will be in v1.0.3-b4. And I have to remove the optifine flag, because I messed up the window rendering meself ;-). You just see it with optifine.

**Comment by ILLOMIURGE** [comment]
Thanks.

**Comment by stfwi** [comment]
Ok, b4 is up. Could you also double check with your setup that the issue is solved?

**Comment by ILLOMIURGE** [comment]
Yep. Totally fixed.

**Comment by stfwi** [comment]
Perfect, thanks for checking. I close this then.

**Comment by WenXin20** [comment]
Hello, with Minecraft v1.14.4, this bug is back. I have Optifine HD U F4 and Engineer's Decor v1.0.16-b5

**Comment by stfwi** [comment]
Hi, the windows are now normal blocks and rendered with the (new) standard Mojang blaze3d. I currently do not see a handle where I could pull to fix it. Can you file this for optifine? (I think that's something to fix in the mod that messes with the graphics of others ;) )
