### ISSUE TITLE
1.16.4 Config not actually changing anything

### ISSUE THREAD

**Issue by Staegrin** [stfwi/engineers-decor#152]
Mod version: engineersdecor-1.16.4-1.1.6-b2
Forge version: 35.1.13

So created 2 worlds In one I used the standard configs, in the other I changed them. Then did some tests and compared the data. They were identical...

Small block breaker
		#Defines how much RF power the Small Block Breaker requires to magnificently increase the processing speed. The config value can be changed on-the-fly for tuning.
		#Range: 4 ~ 1024
		block_breaker_power_consumption = 64
So the standard value of 64 made the total RF cost for breaking a cobblestone equal to 960 RF. Changing the value to the minimum allowed of 4 the total RF cost is still 960 RF.

The same happens with both furnaces. Changing furnace speed, fuel efficiency and power consumption does not change anything.

Small laboratory furnace 
Standard settings:130%speed100%efficiency
Alternate settings:800%speed400%efficiency
Small electrical furnace
Standard settings:250%speed16RF/tick
Alternate settings:800%speed8RF/tick

Speed, fuel and power consumption is equal in both cases even though the settings are completely different. 

Also the config says [Defines, in percent, how fuel efficient the lab furnace is, compared to a vanilla furnace. 100% means vanilla furnace consumiton] consumiton should be consumption and the standard setting of 100% should mean that the small laboratory furnace would have the same fuel usage as a vanilla furnace yet it is more fuel efficient (which I do like).

**Comment by stfwi** [comment]
Hi, is the config you modify the one in the gamesave/server world directory? Except that some log outputs can be rescaled I could not see that it does not work. Do you see, when you save or type "/reload" in the game shell any log entries like this one?
```
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config file changed engineersdecor-server.toml
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config: EXPERIMENTAL FEATURES ENABLED.
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config lab furnace speed:130.0%, efficiency:100.0%
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config chairs sit:true, mob-sit: 10.0%, stand up: 0.01%
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config pipe valve: maxflow:1000mb, redstone amp:20mb/sig
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config electrical furnace speed:500, power consumption:1000
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config small solar panel: Peak production:40/tick
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config block breaker: Boost energy consumption:512rf/t, reluctance=17t/hrdn, break time offset=15t
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config tree cutter: Boost energy consumption:320rf/t, cutting time 1200t.
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config milker: energy consumption:0rf/t
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config fluid funnel: tank-fluid-collection:true
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config dropper: item-insertion:true
[18:48:53] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Opt-outs:sign_decor
```

**Comment by Staegrin** [comment]
The config is on a per world/save basis in the serverconfig folder for that world.
The log states concerning engineer's decor
```
18:19:36.516
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Applying loaded config file.
18:19:36.519
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config lab furnace speed:130.0%, efficiency:100.0%
18:19:36.523
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config chairs sit:true, mob-sit: 10.0%, stand up: 0.01%
18:19:36.558
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config pipe valve: maxflow:1000mb, redstone amp:20mb/sig
18:19:36.558
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config electrical furnace speed:290, power consumption:928
18:19:36.558
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config small solar panel: Peak production:40/tick
18:19:36.558
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config block breaker: Boost energy consumption:64rf/t, reluctance=17t/hrdn, break time offset=15t
18:19:36.558
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config tree cutter: Boost energy consumption:320rf/t, cutting time 1200t.
18:19:36.558
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config milker: energy consumption:0rf/t [milk fluid available]
18:19:36.558
game
[18:19:36] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Config fluid funnel: `tank-fluid-collection:false
```
While the config for that world has the following test values.

```
[server.tweaks]
		#Defines how much time the Small Tree Cutter needs to cut a tree without RF power. The value is in seconds. With energy it is 6 times faster. The config value can be changed on-the-fly for tuning.
		#Range: 10 ~ 240
		tree_cutter_cutting_time_needed = 60
		#Defines how much time the Small Block Breaker needs at least, better said it's an offset: 'reluctance' * hardness + min_time, you change the 'min_time' here, value in ticks.The config value can be changed on-the-fly for tuning.
		#Range: 10 ~ 100
		block_breaker_min_breaking_time = 10
		#Defines, in percent, how fast the electrical furnace smelts compared to a vanilla furnace. 100% means vanilla furnace speed, 150% means the electrical furnace is faster. The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 800
		e_furnace_speed_percent = 800
		#Defines if the electrical furnace automatically pulls items from an inventory at the input side.The config value can be changed on-the-fly for tuning.
		e_furnace_automatic_pulling = true
		#Defines how much time the Small Milking Machine needs work. Note this is a permanent standby power, not only when the device does something. Use zero to disable energy dependency and energy handling of the machine. The config value can be changed on-the-fly for tuning.
		#Range: 0 ~ 1024
		milking_machine_energy_consumption = 0
		#Defines how many millibuckets can be transferred (per tick) through the valves. That is technically the 'storage size' specified for blocks that want to fill fluids into the valve (the valve has no container and forward that to the output block), The value can be changed on-the-fly for tuning. 
		#Range: 1 ~ 32000
		pipevalve_max_flowrate = 1000
		#Defines how much RF power the Small Block Breaker requires to magnificently increase the processing speed. The config value can be changed on-the-fly for tuning.
		#Range: 4 ~ 1024
		block_breaker_power_consumption = 4
		#Defines, in percent, how high the probability is that a mob sits on a chair when colliding with it. Can be changed on-the-fly for tuning.
		#Range: 0.0 ~ 80.0
		chair_mob_sitting_probability_percent = 10.0
		#Defines if the Small Tree Cutter does not work without RF power.
		tree_cutter_requires_power = false
		#Defines, in percent, how fuel efficient the lab furnace is, compared to a vanilla furnace. 100% means vanilla furnace consumiton, 200% means the lab furnace needs about half the fuel of a vanilla furnace, The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 400
		furnace_fuel_efficiency_percent = 400
		#Defines how much RF per tick the the electrical furnace consumed (average) for smelting. The feeders transferring items from/to adjacent have this consumption/8 for each stack transaction. The default value is only slightly higher than a furnace with an IE external heater (and no burning fuel inside).The config value can be changed on-the-fly for tuning.
		#Range: 8 ~ 4096
		e_furnace_power_consumption = 8
		#Defines the peak power production (at noon) of the Small Solar Panel. Note that the agerage power is much less, as no power is produced at all during the night, and the power curve is nonlinear rising/falling during the day. Bad weather conditions also decrease the production. The config value can be changed on-the-fly for tuning.
		#Range: 2 ~ 4096
		small_solar_panel_peak_production = 4096
		#Defines how many millibuckets per redstone signal strength can be transferred per tick through the analog redstone controlled valves. Note: power 0 is always off, power 15 is always the max flow rate. Between power 1 and 14 this scaler will result in a flow = 'redstone slope' * 'current redstone power'. The value can be changed on-the-fly for tuning. 
		#Range: 1 ~ 32000
		pipevalve_redstone_gain = 20
		#Disables increasing/decreasing the crafting grid items by scrolling over the crafting result slot.
		without_crafting_mouse_scrolling = false
		#Defines how much RF power the Small Tree Cutter requires to magnificently increase the processing speed. The config value can be changed on-the-fly for tuning.
		#Range: 4 ~ 1024
		tree_cutter_energy_consumption = 64
		#Defines the energy consumption (per tick) for speeding up the smelting process. If IE is installed, an external heater has to be inserted into an auxiliary slot of the lab furnace. The power source needs to be able to provide at least 4 times this consumption (fixed threshold value). The value can be changed on-the-fly for tuning. The default value corresponds to the IE heater consumption.
		#Range: 2 ~ 1024
		furnace_boost_energy_consumption = 2
		#Defines, in percent, probable it is that a mob leaves a chair when sitting on it. The 'dice is rolled' about every 20 ticks. There is also a minimum Sitting time of about 3s. The config value can be changed on-the-fly for tuning.
		#Range: 0.001 ~ 10.0
		chair_mob_standup_probability_percent = 1.0
		#Defines (for each individual cow) the minimum time between milking.
		#Range: 1000 ~ 24000
		milking_machine_milking_delay = 1000
		#Defines if the Small Block Breaker does not work without RF power.
		block_breaker_requires_power = false
		#Defines, in percent, how fast the lab furnace smelts compared to a vanilla furnace. 100% means vanilla furnace speed, 150% means the lab furnace is faster. The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 800
		furnace_smelting_speed_percent = 800
		#Defines how much time the Small Block Breaker needs per block hardness, means: 'reluctance' * hardness + min_time, you change the 'reluctance' here.The unit is ticks/hardness. The config value can be changed on-the-fly for tuning.
		#Range: 5 ~ 50
		block_breaker_reluctance = 5
```
As you can see especially for furnace values something is going wrong.

**Comment by stfwi** [comment]
Hmm, that's right, just checked, the log prints the internally scaled values, that's confusing. So the e-furnace power consumption basically compensates the heat loss, and the power consumption is scaled with the efficiency value so that it needs more power for faster rates. Since I implemented the speed dial switch in the GUI these settings should be probably made independent.
I gonna see to make this config more transparent for the next release.

**Comment by Staegrin** [comment]
Thank you. 
Currently as I said no matter how low you set the power in the config, consumption stays the same for the same amount smelted. 
While the speed also stays the same, ignoring the config.

The laboratory furnace or the block breaker don't even have a dial like the electric furnace and still ignore given configs.

**Comment by stfwi** [comment]
Oky, sat down a bit on it today and edited the log outputs, and also the E-Furnace power drawing/display. It does not compensate the exact heat loss now with RF, but simply draws the specified power when heating (no effective change, just more continuous). In the GUI of the E-Furnace I added a tooltip when hovering the SOC indication capacitors. Lab Furnace and Breaker look okay. 
*What could have been the issue you saw is the server event order (when the config options are applied in the mod modules), if it was the bug it should be fixed now.*
There is also a creative test block that is an infinite RF source/sink with statistic messages when clicked, so if you're not sure if it's fixed you can also use this block to verify (`engineersdecor:test_block`).

Could you send a quick feedback if the issue is gone for your setup? 
Cheers!

**Comment by Staegrin** [comment]
Tested and something is still not full right. First testworld has severconfigs:
```
[server.tweaks]
		#Defines how much time the Small Tree Cutter needs to cut a tree without RF power. The value is in seconds. With energy it is 6 times faster. The config value can be changed on-the-fly for tuning.
		#Range: 10 ~ 240
		tree_cutter_cutting_time_needed = 60
		#Defines how much time the Small Block Breaker needs at least, better said it's an offset: 'reluctance' * hardness + min_time, you change the 'min_time' here, value in ticks.The config value can be changed on-the-fly for tuning.
		#Range: 10 ~ 100
		block_breaker_min_breaking_time = 10
		#Defines, in percent, how fast the electrical furnace smelts compared to a vanilla furnace. 100% means vanilla furnace speed, 150% means the electrical furnace is faster. The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 800
		e_furnace_speed_percent = 800
		#Defines if the electrical furnace automatically pulls items from an inventory at the input side.The config value can be changed on-the-fly for tuning.
		e_furnace_automatic_pulling = true
		#Defines how much time the Small Milking Machine needs work. Note this is a permanent standby power, not only when the device does something. Use zero to disable energy dependency and energy handling of the machine. The config value can be changed on-the-fly for tuning.
		#Range: 0 ~ 1024
		milking_machine_energy_consumption = 0
		#Defines how many millibuckets can be transferred (per tick) through the valves. That is technically the 'storage size' specified for blocks that want to fill fluids into the valve (the valve has no container and forward that to the output block), The value can be changed on-the-fly for tuning. 
		#Range: 1 ~ 32000
		pipevalve_max_flowrate = 1000
		#Defines how much RF power the Small Block Breaker requires to magnificently increase the processing speed. The config value can be changed on-the-fly for tuning.
		#Range: 4 ~ 1024
		block_breaker_power_consumption = 4
		#Defines, in percent, how high the probability is that a mob sits on a chair when colliding with it. Can be changed on-the-fly for tuning.
		#Range: 0.0 ~ 80.0
		chair_mob_sitting_probability_percent = 10.0
		#Defines if the Small Tree Cutter does not work without RF power.
		tree_cutter_requires_power = false
		#Defines, in percent, how fuel efficient the lab furnace is, compared to a vanilla furnace. 100% means vanilla furnace consumiton, 200% means the lab furnace needs about half the fuel of a vanilla furnace, The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 400
		furnace_fuel_efficiency_percent = 400
		#Defines how much RF per tick the the electrical furnace consumed (average) for smelting. The feeders transferring items from/to adjacent have this consumption/8 for each stack transaction. The default value is only slightly higher than a furnace with an IE external heater (and no burning fuel inside).The config value can be changed on-the-fly for tuning.
		#Range: 8 ~ 4096
		e_furnace_power_consumption = 8
		#Defines the peak power production (at noon) of the Small Solar Panel. Note that the agerage power is much less, as no power is produced at all during the night, and the power curve is nonlinear rising/falling during the day. Bad weather conditions also decrease the production. The config value can be changed on-the-fly for tuning.
		#Range: 2 ~ 4096
		small_solar_panel_peak_production = 4096
		#Defines how many millibuckets per redstone signal strength can be transferred per tick through the analog redstone controlled valves. Note: power 0 is always off, power 15 is always the max flow rate. Between power 1 and 14 this scaler will result in a flow = 'redstone slope' * 'current redstone power'. The value can be changed on-the-fly for tuning. 
		#Range: 1 ~ 32000
		pipevalve_redstone_gain = 20
		#Disables increasing/decreasing the crafting grid items by scrolling over the crafting result slot.
		without_crafting_mouse_scrolling = false
		#Defines how much RF power the Small Tree Cutter requires to magnificently increase the processing speed. The config value can be changed on-the-fly for tuning.
		#Range: 4 ~ 1024
		tree_cutter_energy_consumption = 64
		#Defines the energy consumption (per tick) for speeding up the smelting process. If IE is installed, an external heater has to be inserted into an auxiliary slot of the lab furnace. The power source needs to be able to provide at least 4 times this consumption (fixed threshold value). The value can be changed on-the-fly for tuning. The default value corresponds to the IE heater consumption.
		#Range: 2 ~ 1024
		furnace_boost_energy_consumption = 2
		#Defines, in percent, probable it is that a mob leaves a chair when sitting on it. The 'dice is rolled' about every 20 ticks. There is also a minimum Sitting time of about 3s. The config value can be changed on-the-fly for tuning.
		#Range: 0.001 ~ 10.0
		chair_mob_standup_probability_percent = 1.0
		#Defines (for each individual cow) the minimum time between milking.
		#Range: 1000 ~ 24000
		milking_machine_milking_delay = 1000
		#Defines if the Small Block Breaker does not work without RF power.
		block_breaker_requires_power = false
		#Defines, in percent, how fast the lab furnace smelts compared to a vanilla furnace. 100% means vanilla furnace speed, 150% means the lab furnace is faster. The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 800
		furnace_smelting_speed_percent = 800
		#Defines how much time the Small Block Breaker needs per block hardness, means: 'reluctance' * hardness + min_time, you change the 'reluctance' here.The unit is ticks/hardness. The config value can be changed on-the-fly for tuning.
		#Range: 5 ~ 50
		block_breaker_reluctance = 5
```
Log states on loading an unloading the testworld
```
18:23:45.991
game
[18:23:45] [modloading-worker-10/INFO] [wi.en.ModEngineersDecor/]: Engineer's Decor GIT id #61d0225.
18:23:57.724
game
[18:23:57] [Render thread/INFO] [wi.en.ModEngineersDecor/]: Immersive Engineering also installed ...
18:23:57.725
game
[18:23:57] [Render thread/INFO] [wi.en.ModEngineersDecor/]: Registered 114 blocks.
18:24:02.374
game
[18:24:02] [Render thread/INFO] [wi.en.ModEngineersDecor/]: Registered 18 tile entities.
18:24:02.693
game
[18:24:02] [Render thread/INFO] [wi.en.ModEngineersDecor/]: Registered 1 entities bound to blocks.
18:24:03.437
game
[18:24:03] [Render thread/INFO] [wi.en.ModEngineersDecor/]: Registered 8 containers bound to tile entities.
18:24:50.770
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config chairs: sit:true, mob-sit: 10.0%, standup: 0.01%.
18:24:50.779
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config fluid barrel: capacity:12000mb, transfer-rate:4096mb/t.
18:24:50.781
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config fluid funnel: tank-fluid-collection:false.
18:24:50.784
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config pipe valve: maxflow:1000mb, redstone amp:20mb/sig.
18:24:50.790
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config dropper: item-insertion:true.
18:24:50.794
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config block breaker: Boost energy consumption:64rf/t, reluctance=17t/hrdn, break time offset=15t.
18:24:50.798
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config tree cutter: energy consumption:64rf/t, cutting time:1200t.
18:24:50.801
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config lab furnace speed:130.0%, efficiency:100.0%, boost: 24rf/t.
18:24:50.804
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config electrical furnace speed:290%, heat-loss: 1K/t, heating consumption:16rf/t.
18:24:50.806
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config small solar panel: Peak production:40/t.
18:24:50.810
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config milker: energy consumption:0rf/t [milk fluid available]
18:24:50.813
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config freezer energy consumption:92rf/t, cooldown-rate: 2%/s.
18:24:50.815
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config mineal smelter: energy consumption:92rf/t, heat-up rate: 2%/s.
18:24:50.817
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Config waste incinerator: boost energy consumption:8.
18:24:50.817
game
[18:24:50] [modloading-worker-3/INFO] [wi.en.ModEngineersDecor/]: Opt-outs:sign_decor,test_block
18:24:52.885
game
[18:24:52] [Worker-Main8/INFO] [wi.en.ModEngineersDecor/]: Registering recipe condition processor ...
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config chairs: sit:true, mob-sit: 10.0%, standup: 0.01%.
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config fluid barrel: capacity:12000mb, transfer-rate:4096mb/t.
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config fluid funnel: tank-fluid-collection:false.
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config pipe valve: maxflow:1000mb, redstone amp:20mb/sig.
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config dropper: item-insertion:true.
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config block breaker: Boost energy consumption:4rf/t, reluctance=5t/hrdn, break time offset=10t.
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config tree cutter: energy consumption:64rf/t, cutting time:1200t.
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config lab furnace speed:500.0%, efficiency:400.0%, boost: 4rf/t.
18:31:00.791
game
[18:31:00] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config electrical furnace speed:800%, heat-loss: 1K/t, heating consumption:8rf/t.
```
As expected furnaces apply better speed and efficiency.
with the e furnace using 2272 RF and ~14s to smelt 10 oak logs versus 43616 RF and ~37s in the same world with the previous mod version.
Block breaker also uses less power as expected 40 RF per item instead of 960 RF

But when going to the other test world with the standard serverconfig the values don't go up speed and RF usage stay the same.

Log of loading and using /reload command testworld 2:
```
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config chairs: sit:true, mob-sit: 10.0%, standup: 0.01%.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config fluid barrel: capacity:12000mb, transfer-rate:4096mb/t.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config fluid funnel: tank-fluid-collection:false.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config pipe valve: maxflow:1000mb, redstone amp:20mb/sig.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config dropper: item-insertion:true.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config block breaker: Boost energy consumption:4rf/t, reluctance=5t/hrdn, break time offset=10t.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config tree cutter: energy consumption:64rf/t, cutting time:1200t.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config lab furnace speed:500.0%, efficiency:400.0%, boost: 4rf/t.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config electrical furnace speed:800%, heat-loss: 1K/t, heating consumption:8rf/t.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config small solar panel: Peak production:4096/t.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config milker: energy consumption:0rf/t [milk fluid available]
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config freezer energy consumption:92rf/t, cooldown-rate: 2%/s.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config mineal smelter: energy consumption:92rf/t, heat-up rate: 2%/s.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Config waste incinerator: boost energy consumption:8.
18:47:45.162
game
[18:47:45] [Server thread/INFO] [wi.en.ModEngineersDecor/]: Opt-outs:sign_decor,test_block
18:47:45.164
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config file changed engineersdecor-server.toml
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config chairs: sit:true, mob-sit: 10.0%, standup: 0.01%.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config fluid barrel: capacity:12000mb, transfer-rate:4096mb/t.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config fluid funnel: tank-fluid-collection:false.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config pipe valve: maxflow:1000mb, redstone amp:20mb/sig.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config dropper: item-insertion:true.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config block breaker: Boost energy consumption:4rf/t, reluctance=5t/hrdn, break time offset=10t.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config tree cutter: energy consumption:64rf/t, cutting time:1200t.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config lab furnace speed:500.0%, efficiency:400.0%, boost: 4rf/t.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config electrical furnace speed:800%, heat-loss: 1K/t, heating consumption:8rf/t.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config small solar panel: Peak production:4096/t.
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config milker: energy consumption:0rf/t [milk fluid available]
18:47:45.165
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config freezer energy consumption:92rf/t, cooldown-rate: 2%/s.
18:47:45.166
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config mineal smelter: energy consumption:92rf/t, heat-up rate: 2%/s.
18:47:45.166
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Config waste incinerator: boost energy consumption:8.
18:47:45.166
game
[18:47:45] [Thread-1/INFO] [wi.en.ModEngineersDecor/]: Opt-outs:sign_decor,test_block
```
Even with using the /reload command the speed and RF usage did not change.

**Comment by Staegrin** [comment]
After having closed the game completely and restarting testwold 2 has stated using the standard configs. 
So just closing the world and opening another makes the second world use the serverconfigs of the first for some reason. Is this a general 1.16.4 problem or for this mod specific?
full log: 
https://gist.github.com/Staegrin/c8b043de8edea5e91043594f8036a3ae

**Comment by stfwi** [comment]
I have to be honest I don't know. For the config there are two events I get fired from the Forge ...

https://github.com/stfwi/engineers-decor/blob/61d0225afaa5127579b61e994f89a4441ab20a1f/src/main/java/wile/engineersdecor/ModEngineersDecor.java#L113-L124

..., in both I apply the config with the values that are set then at that time in the corresponding config variables.

When I get the time I'll check if there is a known issue in the Forge, or if there are other things to take into account maybe. 
Thanks for double checking, cheers!

**Comment by Staegrin** [comment]
At least the first world you start after starting the game the serverconfigs will actually thankfully do something. 

Just wanted to let you know with you changing the e-furnace code slightly. With standard config in the old version the e-furnace took ~37 seconds and 43616 RF to cook 10 oak logs. With the new code it does it in ~39 seconds and uses 12864 RF. While I like the changes I did think you should know the difference the code changes created.

**Comment by stfwi** [comment]
Ty for the hint. Aye due to the decoupling of the consumption from the speed setting there is for the e-furnace a difference, as is is less people will probably not complain ;)

**Comment by stfwi** [comment]
Ok, I'll apply the changes then for the next mod version, cheers!
